apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nadeshiko-bot.yaml
namespace: nadeshiko-bot
images:
- name: nadeshiko-bot
  newName: ghcr.io/brigadasos/nadeshikobot
  newTag: v2.3.2
